<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lengkapi Profil Sekarang</name>
   <tag></tag>
   <elementGuidId>d3599396-89a1-4b73-97b5-c51baa0f87cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-cta-yellow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.btn-cta-yellow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9920e5c4-fd91-45f9-8ac7-e176b237da18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-cta-yellow</value>
      <webElementGuid>464009a0-2bcc-4d7c-b48e-0202e16fdafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gotoCTA(this)</value>
      <webElementGuid>5a0c77ba-a703-461a-8857-ec5b9e2bda7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cta</name>
      <type>Main</type>
      <value>/funder/verificationform-rdf</value>
      <webElementGuid>57cb90ae-95cd-48b4-82df-d7a2876cc91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lengkapi Profil Sekarang</value>
      <webElementGuid>03be3321-2cea-4be9-8b8c-a61f03c90487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalLengkapiProfil&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn btn-primary btn-cta-yellow&quot;]</value>
      <webElementGuid>62f5d344-2e19-4bbd-bb23-e08103545d77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='gotoCTA(this)']</value>
      <webElementGuid>b41f4692-779d-4aca-aafb-6ddfd6b26e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalLengkapiProfil']/div/div/div[2]/button</value>
      <webElementGuid>b22fe1b7-32d5-434a-9de6-aabcc52c3afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lengkapi Profilmu Untuk Aktivasi Akun dan RDF (Rekening Dana Funder)'])[1]/following::button[1]</value>
      <webElementGuid>4493b14d-65c0-4fa3-993e-4d9cff7eed44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lengkapi Profil Sekarang']/parent::*</value>
      <webElementGuid>7b80ebe1-6740-4659-bc37-fe646b97bd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/button</value>
      <webElementGuid>4d03e1eb-db42-44bf-8a4a-f69508297aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Lengkapi Profil Sekarang' or . = 'Lengkapi Profil Sekarang')]</value>
      <webElementGuid>b26ae881-e13e-4d78-9cc2-9256038df50d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
