<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mina  ALAMI no-replyalamisharia.co.id</name>
   <tag></tag>
   <elementGuidId>cb2de78d-4110-4ccd-ac89-04ceeeaa6b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='return false;']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bbf030ce-518f-487a-a82d-9b8bae9c246a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>950de714-3a77-4b72-a05d-602fb5250bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>569016c2-d8f5-4e34-aaf1-df172d4d2990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mailbox/rizutest004/1473211546</value>
      <webElementGuid>66d48a71-445a-4259-9624-cf1126ec5dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Open email</value>
      <webElementGuid>49144b66-4688-4910-8b07-f907172aa225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mina | ALAMI &lt;no-reply@alamisharia.co.id></value>
      <webElementGuid>9548629d-9d14-4dcb-b902-f7e8384960be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1473211546&quot;)/td[2]/a[@class=&quot;email&quot;]</value>
      <webElementGuid>1159ad5e-ed4b-4f0e-9dd8-1dc70ad219c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='return false;']</value>
      <webElementGuid>c0f13333-16c1-4cb1-a88c-3f9dd60ae8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1473211546']/td[2]/a</value>
      <webElementGuid>7f880ab0-d298-42ad-b2d9-be6972ec21c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mina | ALAMI &lt;no-reply@alamisharia.co.id>')]</value>
      <webElementGuid>4aa45575-d355-4195-83cf-568b812583ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='in 7 hours'])[1]/following::a[1]</value>
      <webElementGuid>a9413882-ff41-4fd0-a4c2-f974b37a9b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[1]/following::a[1]</value>
      <webElementGuid>a385600f-c8a6-479e-8422-08d5ff48e93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rizutest004@mailnesia.com'])[1]/preceding::a[1]</value>
      <webElementGuid>29ef3464-fdd6-409b-a379-d16b1dd2554f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALAMI Sharia - Aktivasi Akun'])[1]/preceding::a[2]</value>
      <webElementGuid>d871dd30-8294-48f3-94be-ad4148d8285f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mina | ALAMI &lt;no-reply@alamisharia.co.id>']/parent::*</value>
      <webElementGuid>5fafe90f-da0f-4707-b584-429b02fc6266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mailbox/rizutest004/1473211546')]</value>
      <webElementGuid>c58c12aa-1413-4641-ba2b-5534edaec4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>22bb0b11-f8eb-4414-971d-c28046d92a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mailbox/rizutest004/1473211546' and @title = 'Open email' and (text() = 'Mina | ALAMI &lt;no-reply@alamisharia.co.id>' or . = 'Mina | ALAMI &lt;no-reply@alamisharia.co.id>')]</value>
      <webElementGuid>7620c21f-f415-4b88-9266-e5945d7dce28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
