<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap</name>
   <tag></tag>
   <elementGuidId>e9a38322-44b2-47fd-90f2-aa51a18759d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerNamaFunder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registerNamaFunder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8e0030d-6dc0-4206-a70f-cbeff964e322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82cd3986-5038-4a57-bde4-e95d492a7176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>63cdc127-dcd8-4649-8815-901b4e3a4252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerNamaFunder</value>
      <webElementGuid>dfd01fa0-cccb-4043-8374-daedfe06b02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>b1ec8373-94ef-4529-b0a4-96b00b90b94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Lengkap Sesuai e-KTP</value>
      <webElementGuid>7ddf6d0a-e4ca-46c9-88fb-6cae3793b70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerNamaFunder&quot;)</value>
      <webElementGuid>65daeed1-69a0-4040-91ea-e2bded9ace4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registerNamaFunder']</value>
      <webElementGuid>9bf3daf6-4c99-404e-8857-d590c3de9007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div/input</value>
      <webElementGuid>fc2ba99f-c506-4d33-a43c-1e9e6383f83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f73f655f-5de4-4ca3-ae68-d8cbfecbfb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'registerNamaFunder' and @name = 'name' and @placeholder = 'Nama Lengkap Sesuai e-KTP']</value>
      <webElementGuid>6446f1e2-6fa3-4564-a692-607e2b68f527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
