<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya tertarik update info terbaru ALAMI</name>
   <tag></tag>
   <elementGuidId>10712b2a-5405-4328-bb7e-cbb0ad21316f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;langganan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='langganan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24422692-7a9c-433e-944b-74d102fa14aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2d891d38-3e9a-4aa2-b0c7-c8b1357e3483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>langganan</value>
      <webElementGuid>3c7af8ef-d54a-4360-aa90-1e24ee000906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFunderForm&quot;)/div[@class=&quot;wrapper-footer&quot;]/label[@class=&quot;text-light-check&quot;]/input[1]</value>
      <webElementGuid>a5872020-468a-4098-8764-72cc70e9e4ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='langganan']</value>
      <webElementGuid>7ea61bf1-d23f-4571-b796-6d39fc29aebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[2]/label/input</value>
      <webElementGuid>6b78f906-9e42-47b8-aaff-c32a6e59dd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1e6ba943-8481-492f-861b-0543cc911b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'langganan']</value>
      <webElementGuid>b1ec7d80-defa-47e1-9ff1-a0ec5971cec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
