<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Individual</name>
   <tag></tag>
   <elementGuidId>6157b365-c2cf-4ecf-b9be-a573ab9827d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.form-check-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registerFunderForm']/div[5]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e688bca9-6953-486c-b5b7-a008750b1761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>9acc3cc0-ffc5-43e4-8f16-e55bf2efdd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>individuOpt</value>
      <webElementGuid>ae5e89ec-0e32-45d5-8706-52957bfe5438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Individual</value>
      <webElementGuid>3e42d68a-56b3-4f09-8a2b-3c3e77f06e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFunderForm&quot;)/div[@class=&quot;form-group custom-radio&quot;]/div[@class=&quot;form-check form-check-inline&quot;]/label[@class=&quot;form-check-label&quot;]</value>
      <webElementGuid>3f188d1d-c330-4d80-90cc-3107e8b9c342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[5]/div/label</value>
      <webElementGuid>8cae049d-30ae-4ec5-9005-4bdb495d340d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Akun'])[1]/following::label[1]</value>
      <webElementGuid>0bb8f472-adab-4c99-835c-66f81b01c879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagus'])[1]/following::label[2]</value>
      <webElementGuid>1f74a1e9-189b-43e5-b775-71a6f740cfe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institusi'])[1]/preceding::label[1]</value>
      <webElementGuid>d0664568-b150-4236-8497-588732e1fd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referral (Opsional)'])[1]/preceding::label[2]</value>
      <webElementGuid>80f1e0e2-0266-45b1-a396-3d47252a17a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Individual']/parent::*</value>
      <webElementGuid>8387534d-18e3-49ca-90bb-cdb0bd3d64ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label</value>
      <webElementGuid>45dee911-919e-44a0-aa94-66f00533dd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Individual' or . = 'Individual')]</value>
      <webElementGuid>dee8eca5-7552-4b7f-ad67-6d4b3c3e7be5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
