<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Instagram</name>
   <tag></tag>
   <elementGuidId>a20cf686-c1ce-4a95-b4b0-ce65df60176b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='registerReferralId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registerReferralId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27c03c14-aad5-4edc-953b-bb3b4568781d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>a7544bac-7b3d-4f98-bc07-b4d8856f4c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>274fe4aa-50be-47a4-943b-ef317f50a63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c67d51d9-aa48-4050-b0c8-12c2aad19b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                </value>
      <webElementGuid>67d16bb2-2adf-4e08-8ed4-72731628257a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerReferralId&quot;)</value>
      <webElementGuid>fd88bff8-bb13-4c0c-90c5-f276be6d1d78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='registerReferralId']</value>
      <webElementGuid>44b55509-590e-436b-a50e-a977af5aa560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[7]/select</value>
      <webElementGuid>fd60826b-7ed8-482d-91bc-8aebb40e7b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana Kamu tahu ALAMI? (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>a1d6aa9e-651d-4c95-ab9f-aecd26d36dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referral (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>7532bff8-21f3-45a7-b244-cca578fd651e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::select[1]</value>
      <webElementGuid>9b3df857-6820-4240-a06e-282f3f9bbac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar disini'])[1]/preceding::select[1]</value>
      <webElementGuid>6aa880fa-5743-4b27-b47a-17200401c433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a18cfd44-2d88-4580-b3f7-b61e63b44ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'registerReferralId' and @name = 'registerReferralId' and (text() = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ' or . = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ')]</value>
      <webElementGuid>e5d394e4-8fcd-4a7c-a36d-b84af0399a2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
